import type { Destination } from "./types"

export const destinations: Destination[] = [
  {
    imageUrl: "/placeholder.svg?height=400&width=600",
    title: "Taman Mini Indonesia Indah",
    totalScore: 4.6,
    reviewsCount: 164271,
    state: "Daerah Khusus Ibukota Jakarta",
    city: "Jakarta",
    phone: "+62 804 178 9789",
    categoryName: "Wisata Rekreasi dan Keluarga",
    description: "Taman yang memamerkan budaya & alam Indonesia melalui museum, taman, & replika pemandangan terkenal.",
    placeId: "ChIJYaJ20FDtaS4RDNry7LknMQc",
    location: {
      lat: -6.3020386,
      lng: 106.8898924,
    },
    tripDuration: 28,
  },
  {
    imageUrl: "/placeholder.svg?height=400&width=600",
    title: "Losari Beach",
    totalScore: 4.5,
    reviewsCount: 12500,
    state: "Sulawesi Selatan",
    city: "Makassar",
    phone: "+62 411 123456",
    categoryName: "Pantai",
    description: "Pantai terkenal di Makassar dengan pemandangan matahari terbenam yang indah.",
    placeId: "makassar1",
    location: {
      lat: -5.1347,
      lng: 119.4089,
    },
    tripDuration: 10,
  },
  {
    imageUrl: "/placeholder.svg?height=400&width=600",
    title: "Candi Prambanan",
    totalScore: 4.8,
    reviewsCount: 45000,
    state: "Daerah Istimewa Yogyakarta",
    city: "Jogja",
    phone: "+62 274 496401",
    categoryName: "Candi",
    description: "Kompleks candi Hindu terbesar di Indonesia yang dibangun pada abad ke-9.",
    placeId: "jogja1",
    location: {
      lat: -7.752,
      lng: 110.4914,
    },
    tripDuration: 12,
  },
  {
    imageUrl: "/placeholder.svg?height=400&width=600",
    title: "Pantai Kuta",
    totalScore: 4.7,
    reviewsCount: 98000,
    state: "Bali",
    city: "Bali",
    phone: "+62 361 755676",
    categoryName: "Pantai",
    description: "Pantai terkenal di Bali dengan ombak yang cocok untuk berselancar.",
    placeId: "bali1",
    location: {
      lat: -8.718,
      lng: 115.1686,
    },
    tripDuration: 28,
  },
]
