import type { Destination } from "./types"

export const jakartaDestinations: Destination[] = [
  {
    imageUrl: "https://lh5.googleusercontent.com/p/AF1QipNqb2OJuyanejJ7jhEUl_rDJA1RGFKAwwxFtbnO=w426-h240-k-no",
    title: "Taman Mini Indonesia Indah",
    totalScore: 4.6,
    reviewsCount: 164271,
    state: "Daerah Khusus Ibukota Jakarta",
    city: "Kota Jakarta Timur",
    phone: "+62 804 178 9789",
    categoryName: "Wisata Rekreasi dan Keluarga",
    description: "Taman yang memamerkan budaya & alam Indonesia melalui museum, taman, & replika pemandangan terkenal.",
    placeId: "ChIJYaJ20FDtaS4RDNry7LknMQc",
    location: {
      lat: -6.3020386,
      lng: 106.8898924,
    },
    tripDuration: 3,
  },
  {
    imageUrl: "https://lh5.googleusercontent.com/p/AF1QipPlGVmU8PG6IyEQNe_yROnm4sKxtq0l-pc2tBwW=w408-h306-k-no",
    title: "Monumen Nasional",
    totalScore: 4.6,
    reviewsCount: 114792,
    state: "Daerah Khusus Ibukota Jakarta",
    city: "Kota Jakarta Pusat",
    phone: "+62 21 3853040",
    categoryName: "Wisata Budaya dan Sejarah",
    description: "Tugu terkenal yang dibangun untuk memperingati kemerdekaan Indonesia dari penjajahan Belanda.",
    placeId: "ChIJLbFk59L1aS4RyLzp4OHWKj0",
    location: {
      lat: -6.1753924,
      lng: 106.8271528,
    },
    tripDuration: 1,
  },
  {
    imageUrl: "https://lh5.googleusercontent.com/p/AF1QipO4HTw7srjUNyLG9ca0zLaIzaro_5ZDSnPg5Bzj=w408-h306-k-no",
    title: "Taman Impian Jaya Ancol",
    totalScore: 4.5,
    reviewsCount: 44219,
    state: "Daerah Khusus Ibukota Jakarta",
    city: "Jkt Utara",
    phone: "",
    categoryName: "Wisata Rekreasi dan Keluarga",
    description: "Resor keluarga di tepi pantai dengan taman hiburan, wahana air, beberapa hotel, & lapangan golf.",
    placeId: "ChIJcdfvd3T0aS4RWFPBwpxqIIU",
    location: {
      lat: -6.1252747,
      lng: 106.8335569,
    },
    tripDuration: 2,
  },
  {
    imageUrl: "https://lh5.googleusercontent.com/p/AF1QipOktTGvAgljxwLfwgQMeDWoteFLprz9pYLkDCB7=w408-h306-k-no",
    title: "Sea World Indonesia",
    totalScore: 4.5,
    reviewsCount: 43983,
    state: "Daerah Khusus Ibukota Jakarta",
    city: "Jkt Utara",
    phone: "",
    categoryName: "Wisata Rekreasi dan Keluarga",
    description: "Akuarium besar yang modern dengan hiu, aneka pertunjukan memberi makan hewan, kolam sentuh, & toko.",
    placeId: "ChIJG1ytuCIeai4RELSMP0wM6o4",
    location: {
      lat: -6.126601,
      lng: 106.842958,
    },
    tripDuration: 1,
  },
  {
    imageUrl: "https://lh5.googleusercontent.com/p/AF1QipNbR_sFwrMK2RTDgRyzQ53223XL24F9e9b8Lu1C=w408-h725-k-no",
    title: "Taman Fatahillah",
    totalScore: 4.6,
    reviewsCount: 27140,
    state: "Daerah Khusus Ibukota Jakarta",
    city: "Kota Jakarta Barat",
    phone: "",
    categoryName: "Wisata Budaya dan Sejarah",
    description: "Lapangan ramai dikelilingi bangunan bersejarah & museum, dengan pertunjukan jalanan rutin.",
    placeId: "ChIJ7V-PP_8dai4RMqvOj2luU_I",
    location: {
      lat: -6.134669,
      lng: 106.8132041,
    },
    tripDuration: 1,
  },
  {
    imageUrl: "https://lh5.googleusercontent.com/p/AF1QipPvlgMxIajqBZXZ3YSic5lUs287W1wiBsTvk87j=w426-h240-k-no",
    title: "Taman Lapangan Banteng",
    totalScore: 4.7,
    reviewsCount: 26724,
    state: "Daerah Khusus Ibukota Jakarta",
    city: "Kota Jakarta Pusat",
    phone: "",
    categoryName: "Wisata Alam",
    description: "Taman modern dengan jalur lari, taman bermain & amfiteater, plus air mancur & pertunjukan lampu saat malam.",
    placeId: "ChIJA88y_8v1aS4RbfwYWObt98A",
    location: {
      lat: -6.170555,
      lng: 106.8350378,
    },
    tripDuration: 1,
  },
  {
    imageUrl: "https://lh5.googleusercontent.com/p/AF1QipM3S-sFGPzR5K7RYLb1ylYMSjpjARQCVm2uhTiV=w408-h306-k-no",
    title: "Tebet Eco Park",
    totalScore: 4.7,
    reviewsCount: 24677,
    state: "Daerah Khusus Ibukota Jakarta",
    city: "Kota Jakarta Selatan",
    phone: "+62 21 5328454",
    categoryName: "Wisata Alam",
    description: "Area hijau tepi sungai luas dengan jalur joging, taman bermain kecil, dan kios makanan akhir pekan.",
    placeId: "ChIJ1Ugkkm3zaS4RXLLyfr1tc4M",
    location: {
      lat: -6.2373489,
      lng: 106.8529248,
    },
    tripDuration: 1,
  },
  {
    imageUrl: "https://lh5.googleusercontent.com/p/AF1QipOMZodhbzwvDj0TXZmISCVLt8EjuJ7ZPLaKJZvK=w408-h306-k-no",
    title: "Museum Sejarah Jakarta",
    totalScore: 4.6,
    reviewsCount: 22550,
    state: "Daerah Khusus Ibukota Jakarta",
    city: "Kota Jakarta Barat",
    phone: "+62 21 6929101",
    categoryName: "Wisata Budaya dan Sejarah",
    description: "Menempati bangunan dari abad ke-18, museum ini menjadi rumah untuk berbagai pameran tentang sejarah Jakarta.",
    placeId: "ChIJfaWSQv8dai4RRQeMZy0D8BI",
    location: {
      lat: -6.1352,
      lng: 106.8133,
    },
    tripDuration: 1,
  },
  {
    imageUrl: "https://lh5.googleusercontent.com/p/AF1QipNP7zR5pM9iGgJ3f1nHHzm5YjPn3rRqEinw4Mtl=w425-h240-k-no",
    title: "Kawasan Wisata Kota Tua Jakarta",
    totalScore: 4.6,
    reviewsCount: 22257,
    state: "Daerah Khusus Ibukota Jakarta",
    city: "Kota Jakarta Barat",
    phone: "",
    categoryName: "Wisata Budaya dan Sejarah",
    description: "Distrik bersejarah tempat bangunan kolonial Belanda, museum & alun-alun ramai dengan pertunjukan jalanan.",
    placeId: "ChIJ7RcAlCrsaS4RM4GToNQSzt8",
    location: {
      lat: -6.1350687,
      lng: 106.8136795,
    },
    tripDuration: 2,
  },
  {
    imageUrl: "https://lh5.googleusercontent.com/p/AF1QipNT4_qzjJ_yO4ksNq9-_-J5aMNjFLiV1xwAKTK5=w408-h725-k-no",
    title: "Taman Suropati",
    totalScore: 4.6,
    reviewsCount: 21392,
    state: "Daerah Khusus Ibukota Jakarta",
    city: "Kota Jakarta Pusat",
    phone: "",
    categoryName: "Wisata Alam",
    description: "Taman kota yang dibangun tahun 1920 dengan beberapa ukiran & air mancur, jalur paving block & bangku.",
    placeId: "ChIJ-S4F5Bb0aS4RgVq6v81ZM4s",
    location: {
      lat: -6.199387,
      lng: 106.8326333,
    },
    tripDuration: 1,
  },
  {
    imageUrl: "https://lh5.googleusercontent.com/p/AF1QipO1PdLpBQFynh983bd3aeQlPEqwYZyvu-fbu4Cl=w408-h306-k-no",
    title: "Taman Menteng",
    totalScore: 4.5,
    reviewsCount: 20505,
    state: "Daerah Khusus Ibukota Jakarta",
    city: "Kota Jakarta Pusat",
    phone: "",
    categoryName: "Wisata Alam",
    description: "Taman publik seluas 30 hektar dengan kebun, arena bermain, lapangan olahraga, & sumur resapan.",
    placeId: "ChIJKeQOsCL0aS4RLuH7DlpcjaI",
    location: {
      lat: -6.1964087,
      lng: 106.8293106,
    },
    tripDuration: 1,
  },
  {
    imageUrl: "https://lh5.googleusercontent.com/p/AF1QipPayLnr2JfGW0guZjsGkWIKMaRMocfHtjh-1Es=w408-h306-k-no",
    title: "Taman Wisata Alam Mangrove Angke Kapuk",
    totalScore: 4.3,
    reviewsCount: 15942,
    state: "Daerah Khusus Ibukota Jakarta",
    city: "Jkt Utara",
    phone: "+62 811-1787-890",
    categoryName: "Wisata Alam",
    description: "Suaka margasatwa ini memiliki banyak pohon bakau, serta monyet dan berbagai jenis burung.",
    placeId: "ChIJoytQiSUdai4RkGKxmmKQnMM",
    location: {
      lat: -6.1064903,
      lng: 106.7368887,
    },
    tripDuration: 1,
  },
  {
    imageUrl: "https://lh5.googleusercontent.com/p/AF1QipOdVuewzzaFdJRmBBmLQneEFPiHAbJR_ew5Rc_W=w421-h240-k-no",
    title: "Masjid Istiqlal",
    totalScore: 4.8,
    reviewsCount: 14200,
    state: "Daerah Khusus Ibukota Jakarta",
    city: "Kota Jakarta Pusat",
    phone: "+62 21 3811708",
    categoryName: "Tempat Ibadah",
    description: "Masjid terbesar di Asia Tenggara dengan desain kontemporer.",
    placeId: "ChIJHeC1aM71aS4RbAyE1ULw-so",
    location: {
      lat: -6.17017,
      lng: 106.83139,
    },
    tripDuration: 1,
  },
  {
    imageUrl: "https://lh5.googleusercontent.com/p/AF1QipMCqOmlO3v-l1IoMwcBxmhnZ-qpvxHbGYWsSzRN=w408-h544-k-no",
    title: "Katedral Jakarta, Santa Maria Diangkat ke Surga",
    totalScore: 4.8,
    reviewsCount: 12789,
    state: "Daerah Khusus Ibukota Jakarta",
    city: "Kota Jakarta Pusat",
    phone: "+62 21 3519186",
    categoryName: "Tempat Ibadah",
    description: "Tempat ibadah Katolik Roma bergaya Neo-Gotik yang direstorasi, dibangun tahun 1901 dengan 3 menara & 3 altar.",
    placeId: "ChIJrSFu-M71aS4RefySRqf97AM",
    location: {
      lat: -6.1691893,
      lng: 106.8328484,
    },
    tripDuration: 1,
  },
  {
    imageUrl: "https://lh5.googleusercontent.com/p/AF1QipP7pbvp_vsy270AvvnTRzLLw1YsUENuv3TAPe3o=w408-h272-k-no",
    title: "Pantjoran Pantai Indah Kapuk",
    totalScore: 4.7,
    reviewsCount: 12265,
    state: "Daerah Khusus Ibukota Jakarta",
    city: "",
    phone: "",
    categoryName: "Pasar Tradisional dan Pusat Budaya",
    description: "Kumpulan bangunan dengan desain indah yang menampilkan Chinatown tua, dengan toko makanan & kios kaki lima.",
    placeId: "ChIJL2LONqYdai4R8R8LHoOjct8",
    location: {
      lat: -6.0905524,
      lng: 106.7444756,
    },
    tripDuration: 1,
  },
  {
    imageUrl: "https://lh5.googleusercontent.com/p/AF1QipOJd4PusgVB7rUkUdfwSn3vSKMD0sAYEhN_aOiQ=w408-h306-k-no",
    title: "Jakarta AQuarium Safari",
    totalScore: 4.7,
    reviewsCount: 10666,
    state: "Daerah Khusus Ibukota Jakarta",
    city: "Kota Jakarta Barat",
    phone: "+62 21 27893435",
    categoryName: "Wisata Rekreasi dan Keluarga",
    description: "",
    placeId: "ChIJo7n7ffv3aS4RsSNgsHX4e94",
    location: {
      lat: -6.1749533,
      lng: 106.7900155,
    },
    tripDuration: 1,
  },
  {
    imageUrl: "https://lh5.googleusercontent.com/p/AF1QipM18Ag0t21XI-qEKkHYkuktNY_S4IWh8xI2lokc=w408-h270-k-no",
    title: "Taman Ayodia - Barito",
    totalScore: 4.5,
    reviewsCount: 10648,
    state: "Daerah Khusus Ibukota Jakarta",
    city: "Kota Jakarta Selatan",
    phone: "",
    categoryName: "Wisata Alam",
    description: "Taman kecil yang menawan di tengah danau, dengan air mancur & jalan setapak, plus gazebo & pujasera.",
    placeId: "ChIJuTW9y2zxaS4RKwSl9KopVgI",
    location: {
      lat: -6.2453376,
      lng: 106.7945996,
    },
    tripDuration: 1,
  },
  {
    imageUrl: "https://lh5.googleusercontent.com/p/AF1QipNZ7FAyFAF47G1PmYwx4Cr0Tv6GxfB4BrSo9oxZ=w408-h612-k-no",
    title: "Museum Bank Indonesia",
    totalScore: 4.7,
    reviewsCount: 10637,
    state: "Daerah Khusus Ibukota Jakarta",
    city: "Kota Jakarta Barat",
    phone: "+62 812-9157-3940",
    categoryName: "Wisata Budaya dan Sejarah",
    description: "Museum yang menampilkan sejarah perbankan lokal, termasuk mata uang antik & uang kertas internasional.",
    placeId: "ChIJDzlr6wH2aS4Ro2gBJGt31G0",
    location: {
      lat: -6.1371066,
      lng: 106.8129846,
    },
    tripDuration: 1,
  },
  {
    imageUrl: "https://lh5.googleusercontent.com/p/AF1QipNXSMTKDT5iVNwkBlNDai3MGK0BToPEuIoC85_x=w408-h544-k-no",
    title: "KidZania Jakarta",
    totalScore: 4.6,
    reviewsCount: 10519,
    state: "Daerah Khusus Ibukota Jakarta",
    city: "Kota Jakarta Selatan",
    phone: "+62 21 5154888",
    categoryName: "Tempat Bermain Anak-Anak",
    description: "",
    placeId: "ChIJ7Zj-D1HxaS4RTEzBshMYqsk",
    location: {
      lat: -6.2250735,
      lng: 106.8097144,
    },
    tripDuration: 1,
  },
  {
    imageUrl: "https://lh5.googleusercontent.com/p/AF1QipPz_UUE8qI1_JXJB6B8vPqCvGNlIactPMUdzbTH=w426-h240-k-no",
    title: "Atlantis Water Adventures Ancol",
    totalScore: 4.5,
    reviewsCount: 10429,
    state: "Daerah Khusus Ibukota Jakarta",
    city: "Jkt Utara",
    phone: "",
    categoryName: "Wisata Rekreasi dan Keluarga",
    description: "Taman rekreasi air yang luas dengan banyak tanaman & atraksi seperti kolam ombak & tempat bermain apung.",
    placeId: "ChIJSb_ryQeai4Razpg-FOwECI",
    location: {
      lat: -6.12419,
      lng: 106.839134,
    },
    tripDuration: 1,
  }
] 